# patch_nfs_details.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-client-provisioner
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 10.0.0.3
            - name: NFS_PATH
              value: /mnt/user/Kubernetes
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.0.0.3
            path: /mnt/user/Kubernetes
